title: Matthew Davis Online Portfolio
logo: /assets/img/logo.JPG
description: Dynamic Supply Chain and Logistics professional with over five years of experience in managing operational teams, and implementing process improvements. 
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins: 
- jekyll-remote-theme
styles:
  - /assets/css/custom.css