title: Matthew Davis Online Portfolio
logo: /assets/img/IMG_1201.JPG
description: Dynamic Supply Chain and Logistics professional with over 5 years of experience managing inventory, leading operational teams, and implementing process improvements. Recognized for achieving 93% employee engagement and delivering cost-effective solutions in high-pressure environments. Skilled in leveraging advanced WMS platforms and data analysis tools to drive operational efficiency and cost savings.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
